const mockUpUserContacts = [
    {
        "userId": "user1",
        "contactId": "33333333333333333",
        "name": "Benedikt Ziegler", 
        "email": "benedikt@gmail.com",
        "userColor": "var(--purple)", 
        "signature": "BZ",   
    },
    {
        "userId": "user1",
        "contactId": "11111111111111111",
        "name": "Anton Mayer", 
        "email": "antom@gmail.com", 
        "userColor": "var(--mintGreen)",
        "signature": "AM", 
    }, 
    {
        "userId": "user1",
        "contactId": "7777777777777777",
        "name": "Emil Schneck", 
        "email": "eschneck@gmail.com",
        "userColor": "var(--purple)",
        "signature": "ES", 
    },
    {
        "userId": "user1",
        "contactId": "222222222222222",
        "name": "Anja Schulz", 
        "email": "schulz@htomail.com",
        "userColor": "var(--orangeIcons)",
        "signature": "AZ",   
    },
    {
        "userId": "user1",
        "contactId": "666666666666666",
        "name": "Emmanuel Mauer", 
        "email": "emmanuelma@gmail.com",
        "userColor": "var(--greenIcon)",
        "signature": "EM",  
    }, 
    {
        "userId": "user1",
        "contactId": "4444444444444444",
        "name": "David Eisenberg", 
        "email": "davidberg@gmail.com",
        "userColor": "var(--pink)", 
        "signature": "DE",
    },
    {        
        "userId": "user1",
        "contactId": "55555555555555555",
        "name": "Eva Fischer", 
        "email": "eva@gmail.com",
        "userColor": "var(--curry)",
        "signature": "EF",
    },
];
